<form class="form-horizontal" role="form" action="/add/post" method="post">
  <div class="form-group">
    <label for="title" class="col-lg-2 control-label">Title</label>
    <div class="col-lg-10">
      <input type="text" class="form-control" name="title" id="title">
    </div>
  </div>
  <div class="form-group">
    <label for="text" class="col-lg-2 control-label">Text</label>
    <div class="col-lg-10">
        <textarea class="form-control" id="text" name="text" rows="10"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Add post</button>
    </div>
  </div>
</form>